# Generated by Django 4.0 on 2022-02-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_staff_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('M', 'Administrator'), ('P', 'Professor'), ('F', 'Staff'), ('S', 'Student'), ('G', 'Graduate'), ('A', 'Applicant'), ('L', 'Student on a leave of absence')], max_length=1, null=True),
        ),
    ]
