# Generated by Django 4.0 on 2022-02-21 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sis', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='user.TotalStudent'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.basesubject'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'division', 'opening_semester')},
        ),
    ]
